export enum ExportFormat {
  CSV = 'CSV',
  EXCEL = 'EXCEL',
  PDF = 'PDF',
}

export enum StoreOrdersReportSortField {
  CAMPAIGN_NAME = 'CAMPAIGN_NAME',
  STORE_NAME = 'STORE_NAME',
  STORE_NUMBER = 'STORE_NUMBER',
  STORE_ALIAS = 'STORE_ALIAS',
  ITEM_NAME = 'ITEM_NAME',
  QUANTITY = 'QUANTITY',
  ORDER_STATUS = 'ORDER_STATUS',
  ORDER_NUMBER = 'ORDER_NUMBER',
  ORDER_CREATED_AT = 'ORDER_CREATED_AT',
  IS_REORDER = 'IS_REORDER',
  PSP_ORDER_REFERENCE = 'PSP_ORDER_REFERENCE',
  PSP_ACKNOWLEDGED_ON = 'PSP_ACKNOWLEDGED_ON',
  ORDER_LINE_NUMBER = 'ORDER_LINE_NUMBER',
}

export enum ShipmentsTrackingReportSortField {
  SHIPMENT_NUMBER = 'SHIPMENT_NUMBER',
  CAMPAIGN_NAME = 'CAMPAIGN_NAME',
  ORDER_NUMBER = 'ORDER_NUMBER',
  STORE_NAME = 'STORE_NAME',
  STORE_NUMBER = 'STORE_NUMBER',
  TRACKING_NUMBER = 'TRACKING_NUMBER',
  CARRIER_NAME = 'CARRIER_NAME',
  ETA = 'ETA',
  QUANTITY_SHIPPED = 'QUANTITY_SHIPPED',
  SHIPPED_ON = 'SHIPPED_ON',
  DELIVERED_ON = 'DELIVERED_ON',
  SHIPMENT_STATUS = 'SHIPMENT_STATUS',
  PARTIAL_SHIPMENT = 'PARTIAL_SHIPMENT',
}

export enum IssuesReordersReportSortField {
  ISSUE_NUMBER = 'ISSUE_NUMBER',
  CAMPAIGN_NAME = 'CAMPAIGN_NAME',
  STORE_NAME = 'STORE_NAME',
  STORE_NUMBER = 'STORE_NUMBER',
  ITEM_NAME = 'ITEM_NAME',
  ISSUE_TYPE = 'ISSUE_TYPE',
  AFFECTED_QUANTITY = 'AFFECTED_QUANTITY',
  ISSUE_RAISED_ON = 'ISSUE_RAISED_ON',
  APPROVAL_STATUS = 'APPROVAL_STATUS',
  APPROVED_BY = 'APPROVED_BY',
  DECISION_DATE = 'DECISION_DATE',
  REORDER_NUMBER = 'REORDER_NUMBER',
  REPLACEMENT_SHIPMENT_NUMBER = 'REPLACEMENT_SHIPMENT_NUMBER',
}

export enum OpsDashboardMetricsReportSortField {
  WEEK_LABEL = 'WEEK',
  WEEK_START_DATE = 'WEEK_START_DATE',
  TOTAL_SHIPMENTS = 'TOTAL_SHIPMENTS',
  LATE_SHIPMENTS = 'LATE_SHIPMENTS',
  ORDERS_PENDING_FULFILLMENT = 'ORDERS_PENDING_FULFILLMENT',
  REORDER_REQUESTS_RAISED = 'REORDER_REQUESTS_RAISED',
  SLA_COMPLIANCE_PERCENTAGE = 'SLA_COMPLIANCE_PERCENTAGE',
}

export enum CampaignSummaryReportSortField {
  CAMPAIGN_NAME = 'CAMPAIGN_NAME',
  CAMPAIGN_STATUS = 'CAMPAIGN_STATUS',
  CAMPAIGN_START_DATE = 'CAMPAIGN_START_DATE',
  SHIP_BY_DATE = 'SHIP_BY_DATE',
  COMPLETION_PERCENTAGE = 'COMPLETION_PERCENTAGE',
  CAMPAIGN_TYPE = 'CAMPAIGN_TYPE',
  CAMPAIGN_MANAGER_NAME = 'CAMPAIGN_MANAGER_NAME',
  BRAND_NAME = 'BRAND_NAME',
  PSP_NAME = 'PSP_NAME',
  CAMPAIGN_END_DATE = 'CAMPAIGN_END_DATE',
  TOTAL_STORES_ASSIGNED = 'TOTAL_STORES_ASSIGNED',
  STORES_COMPLETED = 'STORES_COMPLETED',
  LATE_SHIPMENTS = 'LATE_SHIPMENTS',
  ANOMALIES_REPORTED = 'ANOMALIES_REPORTED',
  REORDERS_RAISED = 'REORDERS_RAISED',
  PHOTOS_REJECTED = 'PHOTOS_REJECTED',
}

export enum ExecutionProofReportSortField {
  CAMPAIGN_NAME = 'CAMPAIGN_NAME',
  STORE_NAME = 'STORE_NAME',
  PROOF_SUBMITTED_ON = 'PROOF_SUBMITTED_ON',
  PROOF_VERIFICATION_STATUS = 'PROOF_VERIFICATION_STATUS',
  ATTESTED_ON = 'ATTESTED_ON',
  STORE_NUMBER = 'STORE_NUMBER',
  ORDER_NUMBER = 'ORDER_NUMBER',
  ITEM_NAME = 'ITEM_NAME',
  ITEM_QUANTITY = 'ITEM_QUANTITY',
  APPROVED_PHOTO_COUNT = 'APPROVED_PHOTO_COUNT',
  ATTESTED_BY = 'ATTESTED_BY',
}

export enum ExceptionQueueReportSortField {
  ISSUE_NUMBER = 'ISSUE_NUMBER',
  STORE_NAME = 'STORE_NAME',
  EXCEPTION_TYPE = 'EXCEPTION_TYPE',
  DUE_DATE = 'DUE_DATE',
  DAYS_OVERDUE = 'DAYS_OVERDUE',
  REORDER_STATUS = 'REORDER_STATUS',
  STORE_NUMBER = 'STORE_NUMBER',
  CAMPAIGN_NAME = 'CAMPAIGN_NAME',
  SHIPMENT_NUMBER = 'SHIPMENT_NUMBER',
  ASSIGNED_REGIONAL_ADMIN = 'ASSIGNED_REGIONAL_ADMIN',
  LAST_ACTION_TAKEN = 'LAST_ACTION_TAKEN',
  LAST_ACTION_DATE = 'LAST_ACTION_DATE',
  AFFECTED_QUANTITY = 'AFFECTED_QUANTITY',
}

export enum ProofReviewReportSortField {
  STORE_NAME = 'STORE_NAME',
  CAMPAIGN_NAME = 'CAMPAIGN_NAME',
  SUBMISSION_DATE = 'SUBMISSION_DATE',
  REVIEW_STATUS = 'REVIEW_STATUS',
  REVIEW_DATE = 'REVIEW_DATE',
  STORE_NUMBER = 'STORE_NUMBER',
  ITEM_NAME = 'ITEM_NAME',
  REJECTION_REASON = 'REJECTION_REASON',
  REVIEWER_NAME = 'REVIEWER_NAME',
  RETAKE_REQUIRED = 'RETAKE_REQUIRED',
  RETAKE_STATUS = 'RETAKE_STATUS',
  RETAKE_DUE_DATE = 'RETAKE_DUE_DATE',
  PROOF_IMAGE_LINKS = 'PROOF_IMAGE_LINKS',
}

export enum SurveyResponseReportSortField {
  SURVEY_NAME = 'SURVEY_NAME',
  STORE_NAME = 'STORE_NAME',
  RESPONSE_STATUS = 'RESPONSE_STATUS',
  ASSIGNED_AT = 'ASSIGNED_AT',
  SUBMITTED_AT = 'SUBMITTED_AT',
  SURVEY_STATUS = 'SURVEY_STATUS',
  BRAND_NAME = 'BRAND_NAME',
  STORE_NUMBER = 'STORE_NUMBER',
  ASSIGNED_BY = 'ASSIGNED_BY',
  SUBMITTED_BY = 'SUBMITTED_BY',
}

export enum ReportKey {
  STORE_ORDERS = 'STORE_ORDERS',
  SHIPMENTS_TRACKING = 'SHIPMENTS_TRACKING',
  ISSUES_REORDERS = 'ISSUES_REORDERS',
  OPS_DASHBOARD_METRICS = 'OPS_DASHBOARD_METRICS',
  CAMPAIGN_SUMMARY = 'CAMPAIGN_SUMMARY',
  EXECUTION_PROOF = 'EXECUTION_PROOF',
  EXCEPTION_QUEUE = 'EXCEPTION_QUEUE',
  PROOF_REVIEW = 'PROOF_REVIEW',
  SURVEY_RESPONSE = 'SURVEY_RESPONSE',
}
